name: Publish Packages

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Verify NPM_TOKEN
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "NPM_TOKEN is not set. Please configure it in the repository secrets."
            exit 1
          fi

      - name: Verify versions
        run: pnpm scripts:uv

      - name: Build packages
        run: pnpm build

      - name: Prepare packages
        run: pnpm scripts:prepare

      - name: Publish packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm m ls --json --depth=-1 | jq -r '.[].path' | grep '/packages/' | while read -r package; do
            echo "Publishing package: $package"
            cd "$package"
            npm publish --access public --provenance --no-git-checks
            cd -
          done
